### ISSUE TITLE
Support `event.waitUntil`

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1420]
(context: Idea mentioned by @Atinux while debugging a CPU time out issue with cloudflare workers in a request handler doing twice caching on KV)

From [cloudflare docs](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#waituntil)

> The waitUntil command extends the lifetime of the "fetch" event. It accepts a Promise-based task which the Workers runtime will execute before the handler terminates but without blocking the response. For example, this is ideal for [caching responses](https://developers.cloudflare.com/workers/runtime-apis/cache/#put) or handling logging.

We might introduce `event.waitUntil` as a way to declare pending promises that need to be eventually resolved before closing server instance but not blocking request. Examples are logging and caching.

This feature shall be somehow integrated to the runtime providers as well to implement with their native capabilities.

By default we shall use it to wait server closing, logging integration and possibly caching layer.

Tracker:

- [x] `event.waitUntil` (https://github.com/unjs/nitro/issues/1421)
- [x] Cloudflare integration (https://github.com/unjs/nitro/issues/1421)
- [x] Caching layer integration (https://github.com/unjs/nitro/issues/1420)
- [ ] Node.js integration for graceful shutdown

```[tasklist]
### Tasks
- [ ] https://github.com/unjs/nitro/pull/1421
- [ ] https://github.com/unjs/nitro/pull/1422
```
