### ISSUE TITLE
Stable wasm support

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1952]
**UPDATE:** Migrating to https://github.com/unjs/unwasm !

----

Supporting `wasm` modules had been experimental under `experimental.wasm` flag. In order to mark it as stable, we need to ensure it works **consistently** and is well tested.

Reference for wasm esm integration proposal: https://github.com/WebAssembly/esm-integration/tree/main/proposals/esm-integration

```[tasklist]
### Tasks
- [x] https://github.com/unjs/nitro/pull/1951
- [x] Work on Windows (CI failing)
- [x] Working on (supported) workers with native WASM (https://github.com/unjs/nitro/pull/1957)
- [x] Working with ESM Imports (#2017)
- [x] Stability issues
- [x] Allow passing custom importers
```

**Comment by harlan-zw** [comment]
FWIW just some notes on implementing ReSVG, Satori WASM for all edge providers with current implementation features.

## Rollup Plugin

This is what my `loadWASM` util looks like, that wraps the transformation that the rollup wasm plugin does.

```ts
export async function importWasm(input: any) {
  // may be a nested await for some reason
  const _input = await input
  const _module = _input.default || _input
  // this is from rollup/wasm, it does some magic we need to recover from
  if (typeof _module === 'function') {
    // empty input is to avoid instantiating the wasm module
    // this will just compile it
    const fnRes = await _module() // no args
    const _instance = fnRes.instance || fnRes
    return _instance.exports || _instance || _module
  }
  return _module
}
```

```ts
const wasm = importWasm(import('yoga-wasm-web/dist/yoga.wasm' as string))
  .then(async yoga => await initYoga(yoga))
```

Notice I've omitted the options to `_module()`, this is because most WASM's provide their own init function. Calling `new WebAssembly.Instance(mod, {})` on them yourself will throw errors.

We just want the WASM instance `var mod = new WebAssembly.Module(buf)`. Most of these APIs will even just accept the buffer.

Overall I've found the rollup wasm plugin trying to do too much and it ends up causing hard to debug issues.

### esmImport

For Cloudflare (and using it on Vercel Edge), still have issues with `esmImport`, never seems to properly replace the module path.  I have implemented hack that works. (simple search+replace)

```ts
 // HACK: we need to patch the compiled output to fix the wasm resolutions using esmImport
  // TODO replace this once upstream is fixed
  nuxt.hooks.hook('nitro:init', async (nitro) => {
    nitro.hooks.hook('compiled', async (_nitro) => {
      const target = resolveNitroPreset(_nitro.options)
      const compatibility = getPresetNitroPresetCompatibility(target)
      if (compatibility.wasm?.esmImport !== true)
        return
      const configuredEntry = nitro.options.rollupConfig?.output.entryFileNames
      let serverEntry = resolve(_nitro.options.output.serverDir, typeof configuredEntry === 'string'
        ? configuredEntry
        : 'index.mjs')
      if (target === 'cloudflare-pages')
        // this is especially hacky
        serverEntry = resolve(dirname(serverEntry), './chunks/wasm.mjs')
      const contents = (await readFile(serverEntry, 'utf-8'))
      const resvgHash = sha1(await readFile(await resolvePath('@resvg/resvg-wasm/index_bg.wasm')))
      const yogaHash = sha1(await readFile(await resolvePath('yoga-wasm-web/dist/yoga.wasm')))
      const postfix = target === 'vercel-edge' ? '?module' : ''
      const path = target === 'cloudflare-pages' ? `../wasm/` : `./wasm/`
      await writeFile(serverEntry, contents
        .replaceAll('"@resvg/resvg-wasm/index_bg.wasm"', `"${path}index_bg-${resvgHash}.wasm${postfix}"`)
        .replaceAll('"yoga-wasm-web/dist/yoga.wasm"', `"${path}yoga-${yogaHash}.wasm${postfix}"`), { encoding: 'utf-8' })
    })
  })
```

**Comment by pi0** [comment]
Moving the rest of the progress to https://github.com/unjs/unwasm.

Nitro's experimental wasm flag will be removed after a while.
